echo Calling init...
call npm init -y

echo Installing ESLint...
call npm install eslint
call npx eslint --init

echo Installing webpack...
call npm install webpack webpack-cli --save-dev

echo Installing the style/css loader for webpack...
call npm install --save-dev style-loader css-loader

echo Installing html-webpack-plugin...
call npm install --save-dev html-webpack-plugin
